name: Playwright Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Playwright globally
        run: |
          npm install -g @playwright/test
          playwright install --with-deps

      - name: Install project dependencies
        run: npm install

      - name: Run tests with direct path
        run: |
          export PATH=$PATH:$(npm bin)
          npx playwright test
        env:
          CI: true

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3